apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bmif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bmif
    app.kubernetes.io/part-of: byoc-app-ucgy
  name: bmif
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: bmif
status:
  loadBalancer: {}
